config/routes.rb
Rails.application.routes.draw do
  get 'weather/index'
  get 'weather/current'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "weather#index"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/weather_controller.rb
# frozen_string_literal: true

# Controller for handling weather-related actions.
class WeatherController < ApplicationController
  # Clears alert and notice messages before certain actions.
  before_action :clear_notices, :set_form_fields

  # Renders the index view.
  def index
  end

  # Retrieves and displays current weather based on user-input parameters.
  #
  # If valid parameters are provided, it sets instance variables for the view,
  # caches the weather data, and renders the current view. Otherwise, it alerts
  # the user about missing or invalid parameters and renders the index view.
  #
  # @raise [StandardError] Reraised to render Rails error page.
  def current
    if valid_params?
      @zip_code, _ = weather_params[:zip_code].split("-")

      flash.notice = "Cached"
      @weather = Rails.cache.fetch(@zip_code.to_s, expires_in: 30.minutes) do
        flash.notice = nil
        weather_connector.call(zip: @zip_code)
      end
    else
      alert_invalid_params
      render :index
    end
  rescue StandardError => e
    Rails.logger.error("Something went wrong. Details: #{e.message}")
    # TODO: create alert
    flash.alert = "Something went wrong. Please check you input and try again later."
    render :index
  end

  private

  # Sets instance variables for form fields based on user-input parameters.
  def set_form_fields
    @street = weather_params[:street]
    @city = weather_params[:city]
    @state = weather_params[:state]
    @zip_code = weather_params[:zip_code]
  end

  # Checks if the provided parameters are valid.
  #
  # Parameters are considered valid if all required parameters are present,
  # and the zip code follows the correct format.
  #
  # @return [Boolean] True if parameters are valid, false otherwise.
  def valid_params?
    required_params.all? { |p| weather_params[p].present? } &&
      valid_zip?
  end

  # Checks if the provided zip code is in the correct format.
  #
  # @return [Boolean] True if the zip code is in the correct format, false otherwise.
  def valid_zip?
    weather_params[:zip_code].to_s.match?(/^\d{5}(\-\d{4})?$/)
  end

  # Alerts the user about missing or invalid parameters.
  def alert_invalid_params
    missing_params = required_params.select { |p| weather_params[p].blank? }
    missing_param_names = missing_params
      .map { |p| p.to_s.humanize }.join(", ")

    message = ""
    message += "Missing #{missing_param_names}. " if missing_params.any?
    message += "Invalid zip code." if weather_params[:zip_code].present? && !valid_zip?

    flash.alert = message.strip
  end

  # Clears alert and notice messages.
  def clear_notices
    flash.alert = nil
    flash.notice = nil
  end

  # Retrieves the OpenWeatherConnector instance.
  #
  # @return [Services::OpenWeatherConnector] The OpenWeatherConnector instance.
  def weather_connector
    @weather_connect ||= Services::OpenWeatherConnector.new
  end

  # Retrieves the permitted weather parameters.
  #
  # @return [ActionController::Parameters] Permitted weather parameters.
  def weather_params
    params.permit(*required_params)
  end

  # Defines the required parameters for weather-related actions.
  #
  # @return [Array<Symbol>] Array of symbols representing required parameters.
  def required_params
    [:street, :city, :state, :zip_code]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/weather_helper.rb
module WeatherHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weather</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="d-flex flex-column justify-content-center align-items-center">
      <div class="mt-2" style="color: green">
        <span class="notice"><%= notice %></span>
      </div>
      <div class="mt-2" style="color: red">
        <span class="alert"><%= alert %></span>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/weather/_form.html.erb
<%= form_with url: weather_current_path, method: :get do |form| %>
  <div class="form-group">
    <%= form.label :street, style: "display: block" %>
    <%= form.text_field :street, class: "form-control", value: @street %>
  </div>
  <div class="form-group">
    <%= form.label :city, style: "display: block" %>
    <%= form.text_field :city, class: "form-control", value: @city %>
  </div>
  <div class="form-group">
    <%= form.label :state, style: "display: block" %>
    <%= form.text_field :state, class: "form-control", value: @state %>
  </div>
  <div class="form-group">
    <%= form.label :zip_code, style: "display: block" %>
    <%= form.text_field :zip_code, class: "form-control", value: @zip_code %>
  </div>
  <div class="mt-4 d-flex justify-content-center">
    <%= form.submit "Submit", class: "btn btn-lg btn-primary rounded-pill" %>
  </div>
<% end %>

app/views/weather/current.html.erb
<div class="text-center">
  <h1 class="mt-4">Current Weather for <%= @weather[:city_name] || @zip_code %></h1>
  <h2><%= @weather[:description].capitalize %></h2>

  <div class="card mt-4">
    <div class="card-body">
      <h3 class="card-title">Temperatures</h3>
      <p class="card-text">Current: <%= @weather[:temp] %>°F</p>
      <p class="card-text">Feels Like: <%= @weather[:feels_like] %>°F</p>
      <p class="card-text">Low: <%= @weather[:temp_min] %>°F</p>
      <p class="card-text">High: <%= @weather[:temp_max] %>°F</p>
    </div>
  </div>
</div>

app/views/weather/index.html.erb
<h1 class="mt-4">Get Current Weather</h1>

<%= render "form" %>